server:
  port: 2233
#  ssl:
#    key-store: classpath:renrenzi.top.pfx #拷贝到根目录的证书文件
#    key-store-password: NtnB5ewk!3DtV!c  #密码(下载tomcat证书压缩包里的txt文件)
#    key-store-type: PKCS12       #固定写法
spring:
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://120.39.217.37:3306/blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: junjie2002
  redis:
    database: 0
    host: 120.39.217.37
    port: 6379
    password: junjie2002
mybatis-plus:
  type-aliases-package: com.jj.jblog.entity
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level.com.jj.jbolg: debug
