server:
  port: 2233

spring:
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://120.39.217.37:3306/blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: 你的账号
    password: 你的密码
  redis:
    database: 0
    host: 你的redishost
    port: 6379
    password: 你的Redis密码
mybatis-plus:
  type-aliases-package: com.jj.jblog.entity
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level.com.jj.jbolg: debug
